### PR TITLE
Introduce dict callback

### PR DESCRIPTION
**Pull request by summerswallow-whi**
This is the dict callback I plan to introduce to plotly dash.

I believe it is more pythonic. Definitely easier to maintain code. I refactored it to support pattern matching as well.

I still need to write some tests up to test the various scenarios.

### CODE REVIEW

**Comment by boludo00** [comment]
maybe we should introduce some examples, some working example dashboard utilizing this callback

**Comment by boludo00** [comment]
I think there might be a little hiccup in getitng a working example. See:
image

Might need to rethink how the context is captured inside the actual Dash instance. 
I see theres a `_callback_context.py` file setting the `callback_context` property but not sure what the best way is to grab it.

**Comment by tashrifbillah** [comment]
Hi, is there an example that demonstrates this function?

**Comment by summerswallow-whi** [comment]
I ended up implementing this as a dash plugin. See https://github.com/WestHealth/dash-dict-callback. Plenty of examples there.

**Comment by tashrifbillah** [comment]
Thank you Haw. I found what I needed already:
https://dash.plotly.com/pattern-matching-callbacks

**Comment by summerswallow-whi** [comment]
@tashrifbillah I'm glad pattern-matching-callbacks work for you. The dict-callback is designed to replace the @callback decorator and have the callbacks received dictionaries and produce dictionaries rather than list. It is 100% compatible with pattern-matching-callbacks should you wish to try it.

**Pull request merged**
